export const Colors = {
    lighterPink:'#ffd1d9',
    lightPink:'#ffa1b2',
    pink:'#ff3c5f',
    pinker:'#ff0532',
    gray:'#9c9c9c',
    lightGray:'#f0f0f0',
    lighterGray:'#f9f9f9',
    darkGray:'#414141',
    white:'#fcfcfc',
    blue:'#d1efff',
    yellow:'#feffd2',
    green:'#d3ffe5',
    purple:'#ffe8ff',
}